### ISSUE TITLE
Complain Queue UI

### ISSUE THREAD

**Issue by LalitKumar-2001** [EnigmaVSSUT/Waste-Management-Client#10]
- List of all active complaints 
- List of all completed complaints 
- These lists should be present as sections in the main screen for users to view

For reference view these designs 
1. [Design-1](https://dribbble.com/shots/18469102-GBL-Complaint-Management-System)
2. [Design-2](https://dribbble.com/shots/5402553-Complaint-Analysis-Table-View)
3. [Design-3](https://dribbble.com/shots/8222892-Telecom-Dashboard-Design)
4. [Design-4](https://dribbble.com/shots/12449426-Online-Complaint-Portal)

Add your design to the UI directory as 'Queue_name'

**Comment by Suraj052** [comment]
I want to contribute to this issue.

**Comment by Suraj052** [comment]
Issue #10 resolved.

**Comment by LalitKumar-2001** [comment]
PR #15 reviewed and merged. 
Added Hacktoberfest label
