### ISSUE TITLE
Footer UI Required

### ISSUE THREAD

**Issue by LalitKumar-2001** [EnigmaVSSUT/Waste-Management-Client#11]
- Footer with social media handles
- Contact us sub-section in the footer section
- Take reference from the following designs:
  -  [Design-1](https://dribbble.com/shots/17267389-Footer-for-a-SaaS-marketing-site)
  -  [Design-2](https://dribbble.com/shots/17354092-We-re-suckers-for-footers)
  -  [Design-3](https://dribbble.com/shots/5620568-Big-footers)
  -  [Design-4](https://dribbble.com/shots/17987753--Banner-Exploration)
  - [Design-5](https://dribbble.com/shots/3018523-Footers-are-my-favorite)
  
  Add your design in the UI directory as 'Footer_name'.

**Comment by swapnil-092** [comment]
I want to contribute to this.

**Comment by LalitKumar-2001** [comment]
Happy Contributing !
