### ISSUE TITLE
Client Side UI

### ISSUE THREAD

**Issue by LalitKumar-2001** [EnigmaVSSUT/Waste-Management-Client#4]
- Create a simplified UI for client side
- Minimal Design
- Material UI should be Used

**Comment by iamsmruti** [comment]
Describe the UI a little more in detail/

**Comment by LalitKumar-2001** [comment]
The UI should include a header where there should be an option for client to post a complaint.
The client could see all the present complaints. 
The present complaints section should include
- Complaint Number and Type
- Date & Time
- Dustbin Number
- Description
- Status ('Pending' or 'Under Process')

**Comment by LalitKumar-2001** [comment]
Completed by @SamSoham through PR #22.
